name: CI

on:
  pull_request:
  push:
    branches: [main, v*]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toolchain: [stable, nightly]

    steps:
      - uses: actions/checkout@v4

      - run: |
          rustup update
          rustup default ${{ matrix.toolchain }}
          rustup component add rustfmt  ### required for rusty_mujoco to build ###
 
      - name: install mujoco and set MUJOCO_DIR
        run: |
          mkdir -p $HOME/.mujoco
          cd $HOME/.mujoco
          wget https://github.com/google-deepmind/mujoco/releases/download/3.3.2/mujoco-3.3.2-linux-x86_64.tar.gz
          tar -xzf mujoco-3.3.2-linux-x86_64.tar.gz
          echo "MUJOCO_DIR=$HOME/.mujoco/mujoco-3.3.2" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$HOME/.mujoco/mujoco-3.3.2/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          
      - run: cargo build
